
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayushi
 */
public class welcome extends javax.swing.JFrame {
      Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    int l;
    
    /**
     * Creates new form welcome
     */
    public welcome() {
  
    initComponents();
    conn = sqlite.ConnecrDb();
    gettrack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        time1 = new cambodia.raven.Time();
        time2 = new cambodia.raven.Time();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(509, 85, 191, 33);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RC NO.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(197, 83, 120, 33);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FULL NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(197, 175, 147, 24);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(509, 168, 191, 31);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLACE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(197, 266, 82, 24);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FORUM", "VR", "PENIOX" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(509, 244, 191, 30);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE OF PARKING");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(197, 355, 235, 24);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIME IN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(197, 431, 101, 24);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TIME OUT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(197, 523, 128, 24);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(684, 442, 159, 28);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(684, 565, 159, 28);

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LAP NO.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(197, 649, 102, 24);

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TRACK NO.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(197, 737, 140, 24);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(509, 649, 204, 31);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(509, 731, 204, 30);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SLOT BOOKING");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(333, 27, 302, 36);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(234, 864, 95, 27);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton2.setText("BOOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(489, 864, 91, 27);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton3.setText("PAYMENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(734, 864, 127, 27);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE NO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(197, 807, 129, 23);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(509, 804, 204, 32);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(501, 340, 200, 30);
        getContentPane().add(time1);
        time1.setBounds(500, 410, 122, 80);
        getContentPane().add(time2);
        time2.setBounds(500, 520, 122, 80);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\2.jpeg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -110, 1000, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    
    public void gettrack()
    {
    try
    {
      String sql="select * from laps where status='"+str+"'";  
       pst = conn.prepareStatement(sql);
       rs=pst.executeQuery();
       if(rs.next())
       {
           String add1=rs.getString("lap");
           jTextField5.setText(add1);
           String add2=rs.getString("track");
           jTextField6.setText(add2);
       }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    }
    public void updatedata()
    {
        try{
            String a1=jTextField5.getText();
            String a2=jTextField6.getText();
            pst = conn.prepareStatement("update laps set status='"+str2+"'where lap='"+a1+"' and track='"+a2+"'");
            pst.executeUpdate();
            
        }
        catch(Exception e)
                {
                  JOptionPane.showMessageDialog(null, e);
                }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql="insert into slots(rc,name,place,date,lap,track,phone)values(?,?,?,?,?,?,?)";
             pst = conn.prepareStatement(sql);
             pst.setString(1,jTextField1.getText());
              pst.setString(2,jTextField2.getText());
               pst.setString(3,(String)jComboBox1.getSelectedItem());
               pst.setString(4,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
               //pst.setString(5,jTextField);
               //pst.setString(6,time2.getText());
                  pst.setString(5,jTextField5.getText()); 
                  pst.setString(6,jTextField6.getText());
                  pst.setString(7,jTextField7.getText());
                  
                  pst.executeUpdate();
                   updatedata();
                  JOptionPane.showMessageDialog(null,"YOUR CAR SLOT  IS BOOKED");
                 // mess();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        try {
			// Construct data
			String apiKey = "apikey=" + "TE9336DjCB0-wbioZ6uhhWMkM9f7HtjN74Yo3dhSAG";
                        l=(int)(Math.random()*10000);
                        String a=jTextField5.getText();
                        String b=jTextField6.getText();
			String message = "&message=" + "PARKING MAINA:YOUR CAR SLOT IS"+" LAPNO "+a+" TRACKNO "+b;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" + jTextField7.getText();
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				stringBuffer.append(line);
			}
			rd.close();
			
			
		} catch (Exception e) {
			System.out.println("Error SMS "+e);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    jTextField1.setText("");
 jTextField2.setText("");
  jTextField3.setText("");
   jTextField4.setText("");
    jTextField5.setText("");
     jTextField6.setText("");
      jTextField7.setText("");
      ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Pay p=new Pay();
                    this.setVisible(false);
                     p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private cambodia.raven.Time time1;
    private cambodia.raven.Time time2;
    // End of variables declaration//GEN-END:variables
String str="AVAIL";
String str2="RESERVED";
}
